apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: "{{ .Values.global.imageRegistry }}/redhat/redhat-operator-index:v4.12"
  sourceType: grpc
  displayName: MDTU-DDM
