apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: {{ .Values.logging_operator_channel | quote }}
  name: cluster-logging
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
